using System;
using System.Collections.Generic;
using System.IO;
using DataLayer.EfClasses;
using NUnit.Framework;

namespace TEC_TestCase
{
    [TestFixture]
    public class CompanyTest
    {
        [Test]
        public void Company_AddNewCompanyWithAutoGeneratedId()
        {
            using var context = new TecContext();

            var newCompany = new Company();
            newCompany.CompanyName = "Soft World";

            context.Add(newCompany);
            context.SaveChanges();

            Console.WriteLine($"ID: {newCompany.CompanyId}\tName: {newCompany.CompanyName}");
        }

        private static IList<Company> Company_ReadFromCSV(string location)
        {
            var sr = new StreamReader(location);
            
            var companyList = new List<Company>();

            string s = sr.ReadLine();

            while (s != null)
            {
                var split = s.Split(',');
                var newCompany = new Company
                {
                    CompanyName = split[0],
                    CompanyAddress = split[1]
                };

                companyList.Add(newCompany);

                s = sr.ReadLine();
            }

            return companyList;
        }

        [Test]
        public static void GenerateCompanies()
        {
            var companies =
                Company_ReadFromCSV(@"C:\Users\Admin\Desktop\2nd Sem '19\Software Design\Project\Data\Company.CSV");

            using var context = new TecContext();

            foreach (var company in companies)
            {
                context.Add(company);
                context.SaveChanges();
            }
        }

        [Test]
        public void ViewCompanies()
        {
            var companies =
                Company_ReadFromCSV(@"C:\Users\Admin\Desktop\2nd Sem '19\Software Design\Project\Data\Company.CSV");


            foreach (var company in companies)
            {
                Console.WriteLine(company.CompanyName);
            }
        }

    }
}